# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d4c4f0fcfcfaf9d54ca04915db4792cd2632b6ad801385f0e7d207e7f11f695898f42d200cf07cfb75caef6389ea32998d5544fa75432b6ab907bdc55d45c62c

test:
  secret_key_base: 905cd55aba9c7b0e0616a757b98d4edd831a86015a3f6f6efcd172a81e5b661e1ab2417c74d894ccf8a08e5ee1f6a1c5a781f4d7ae7f2e6aa70d1d7ac4827555

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
